export const formDefaults = {
    kakaoId: '',
    userType: '',
    username: '',
    age: '',
    phoneNum: '',
    address: '',
    detailAddress: '',
    talk: '',
    eat: '',
    toilet: '',
    bath: '',
    walk: '',
    story: '',
    shareLocation: false,
    certificationImage: null,
    issueYear: '',
    issueMonth: '',
    issueDay: '',
    issueDate: '',
    identityFront: '',
    identityBack: '',
  };